private-events/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :events, only: %i[index new create]
end

private-events/app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_and_belongs_to_many :attendees, class_name: 'User', through: :events_users
end

private-events/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', inverse_of: 'creator'
  has_and_belongs_to_many :attended_events, class_name: 'Event', through: :events_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

private-events/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  # Notice the name of the method
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:login, :username, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

private-events/app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    current_user.events.create(events_params)

    redirect_to root_path
  end

  private

  def events_params
    params.require(:event).permit(:title, :description, :date)
  end
end

private-events/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @events = current_user.events
  end
end

private-events/app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

private-events/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

private-events/app/views/events/index.html.erb
<h1>Events:</h1>

<% @events.each do |event| %>
  <%= event.title %><br>
  <%= event.creator.username %><br>
  <%= event.description %><br>
  <%= event.date %><br>
  --------------------------<br>
<% end %><br>

<%= link_to 'Add event', new_event_path %>

private-events/app/views/events/new.html.erb
<h1>Create event:</h1>

<%= form_with model: @event do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :date %><br>
  <%= f.date_field :date %><br>
  <%= f.submit %>
<% end %>

private-events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <nav>
      <% if current_user %>
        <%= link_to 'Log out', destroy_user_session_path, data: { turbo_confirm: 'Are you sure?', turbo_method: :delete } %>
        <%= link_to 'Update profile', edit_user_password_path %>
      <% end %>
      <% unless current_user %>
        <%= link_to 'Sign in', new_user_session_path %>
        <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>